AndLetgo/2nd-Main-JeonsiLog-Server

- .github/workflows/deploy.yml
- src/main/java/depth/jeonsilog/domain/alarm/domain/Alarm.java
- src/main/java/depth/jeonsilog/domain/alarm/domain/AlarmType.java
- src/main/java/depth/jeonsilog/domain/auth/domain/Token.java
- src/main/java/depth/jeonsilog/domain/calendar/domain/Calendar.java
- src/main/java/depth/jeonsilog/domain/common/BaseEntity.java
- src/main/java/depth/jeonsilog/domain/common/Status.java
- src/main/java/depth/jeonsilog/domain/exhibition/domain/Exhibition.java
- src/main/java/depth/jeonsilog/domain/exhibition/domain/OperatingKeyword.java
- src/main/java/depth/jeonsilog/domain/exhibition/domain/PriceKeyword.java
- src/main/java/depth/jeonsilog/domain/follow/domain/Follow.java
- src/main/java/depth/jeonsilog/domain/image/domain/Image.java
- src/main/java/depth/jeonsilog/domain/interest/domain/Interest.java
- src/main/java/depth/jeonsilog/domain/place/domain/ClosedDays.java
- src/main/java/depth/jeonsilog/domain/place/domain/Place.java
- src/main/java/depth/jeonsilog/domain/rating/domain/Rating.java
- src/main/java/depth/jeonsilog/domain/reply/domain/Reply.java
- src/main/java/depth/jeonsilog/domain/report/domain/Report.java
- src/main/java/depth/jeonsilog/domain/report/domain/ReportType.java
- src/main/java/depth/jeonsilog/domain/review/domain/Review.java
- src/main/java/depth/jeonsilog/domain/s3/presentation/S3Controller.java
- src/main/java/depth/jeonsilog/domain/user/domain/Role.java
- src/main/java/depth/jeonsilog/domain/user/domain/User.java
> [FEAT]: 폴더 구조 및 엔티티 세팅

- src/main/java/depth/jeonsilog/domain/report/domain/Report.java
> [FEAT]: Report - isChecked 컬럼 추가

- src/main/java/depth/jeonsilog/domain/auth/application/AuthService.java
- src/main/java/depth/jeonsilog/domain/auth/dto/AuthRequestDto.java
- src/main/java/depth/jeonsilog/domain/auth/dto/AuthResponseDto.java
- src/main/java/depth/jeonsilog/domain/auth/presentation/AuthController.java
- src/main/java/depth/jeonsilog/domain/exhibition/domain/Exhibition.java
- src/main/java/depth/jeonsilog/domain/rating/domain/Rating.java
- src/main/java/depth/jeonsilog/domain/review/domain/Review.java
- src/main/java/depth/jeonsilog/domain/user/application/UserService.java
- src/main/java/depth/jeonsilog/domain/user/converter/UserConverter.java
- src/main/java/depth/jeonsilog/domain/user/domain/User.java
- src/main/java/depth/jeonsilog/domain/user/domain/repository/UserRepository.java
- src/main/java/depth/jeonsilog/domain/user/dto/UserRequestDto.java
- src/main/java/depth/jeonsilog/domain/user/dto/UserResponseDto.java
- src/main/java/depth/jeonsilog/domain/user/presentation/UserController.java
- src/main/java/depth/jeonsilog/global/config/security/SecurityConfig.java
- 프로필 사진 변경은 s3 개발 이후에 진행하겠습니다.
- `@Where(clause = "status = 'ACTIVE'")` 를 엔티티에 적용시켜 `Soft Delete` 된 데이터는 조회되지 않게 했습니다. 추후 {엔티티} 삭제 API를 개발할 때는 해당 엔티티에 어노테이션을 적용시켜야 합니다.
Closes #11
> ✨ [FEAT]: User API 개발

- src/main/java/depth/jeonsilog/domain/exhibition/domain/Exhibition.java
- src/main/java/depth/jeonsilog/domain/exhibition/domain/repository/ExhibitionRepository.java
- src/main/java/depth/jeonsilog/domain/interest/application/InterestService.java
- src/main/java/depth/jeonsilog/domain/interest/converter/InterestConverter.java
- src/main/java/depth/jeonsilog/domain/interest/domain/repository/InterestRepository.java
- src/main/java/depth/jeonsilog/domain/interest/dto/InterestResponseDto.java
- src/main/java/depth/jeonsilog/domain/interest/presentation/InterestController.java
- src/main/java/depth/jeonsilog/domain/place/domain/repository/PlaceRepository.java
- src/main/java/depth/jeonsilog/domain/rating/application/RatingService.java
- src/main/java/depth/jeonsilog/domain/rating/converter/RatingConverter.java
- src/main/java/depth/jeonsilog/domain/rating/domain/Rating.java
- src/main/java/depth/jeonsilog/domain/rating/domain/repository/RatingRepository.java
- src/main/java/depth/jeonsilog/domain/rating/dto/RatingRequestDto.java
- src/main/java/depth/jeonsilog/domain/rating/dto/RatingResponseDto.java
- src/main/java/depth/jeonsilog/domain/rating/presentation/RatingController.java
- src/main/java/depth/jeonsilog/domain/review/application/ReviewService.java
- src/main/java/depth/jeonsilog/domain/review/converter/ReviewConverter.java
- src/main/java/depth/jeonsilog/domain/review/domain/Review.java
- src/main/java/depth/jeonsilog/domain/review/domain/repository/ReviewRepository.java
- src/main/java/depth/jeonsilog/domain/review/dto/ReviewRequestDto.java
- src/main/java/depth/jeonsilog/domain/review/dto/ReviewResponseDto.java
- src/main/java/depth/jeonsilog/domain/review/presentation/ReviewController.java
- src/main/java/depth/jeonsilog/domain/user/application/UserService.java
- 말씀드렸던대로 페이징 처리가 필요한 부분은 전체적인 개발이 완료된 후 추가 작업하겠습니다.
- `Reply` 까지 작업해서 올리려고 했는데 pr 단위도 너무 커지는 것 같고 늦어질 것 같아서 이렇게 올리겠습니다. `Exhibition`이랑 `Place`까지 해서 4차 배포하는 것으로 해요!
Closes #18 #19 #20
> ✨ [FEAT]: 즐겨찾기, 별점, 감상평 API 개발

- src/main/java/depth/jeonsilog/domain/exhibition/presentation/ExhibitionController.java
- src/main/java/depth/jeonsilog/domain/follow/presentation/FollowController.java
- src/main/java/depth/jeonsilog/domain/interest/presentation/InterestController.java
- src/main/java/depth/jeonsilog/domain/place/presentation/PlaceController.java
- src/main/java/depth/jeonsilog/domain/rating/presentation/RatingController.java
- src/main/java/depth/jeonsilog/domain/reply/application/ReplyService.java
- src/main/java/depth/jeonsilog/domain/reply/converter/ReplyConverter.java
- src/main/java/depth/jeonsilog/domain/reply/domain/Reply.java
- src/main/java/depth/jeonsilog/domain/reply/domain/repository/ReplyRepository.java
- src/main/java/depth/jeonsilog/domain/reply/dto/ReplyRequestDto.java
- src/main/java/depth/jeonsilog/domain/reply/dto/ReplyResponseDto.java
- src/main/java/depth/jeonsilog/domain/reply/presentation/ReplyController.java
- src/main/java/depth/jeonsilog/domain/review/application/ReviewService.java
- src/main/java/depth/jeonsilog/domain/review/presentation/ReviewController.java
- src/main/java/depth/jeonsilog/domain/user/presentation/UserController.java
- src/main/resources/application.yml
- Reply 클래스에 BaseEntity 상속이 안되어있어서 추가했습니다. 추후에 rds에서 create, modified date, status 컬럼 추가할 필요가 있습니다.
- ReviewService에 validateReviewById() 추가했습니다.
Closes #23
> ✨ [FEAT]: Reply API 개발

- src/main/java/depth/jeonsilog/domain/report/application/ReportService.java
- src/main/java/depth/jeonsilog/domain/report/converter/ReportConverter.java
- src/main/java/depth/jeonsilog/domain/report/domain/Report.java
- src/main/java/depth/jeonsilog/domain/report/domain/repository/ReportRepository.java
- src/main/java/depth/jeonsilog/domain/report/dto/ReportRequestDto.java
- src/main/java/depth/jeonsilog/domain/report/dto/ReportResponseDto.java
- src/main/java/depth/jeonsilog/domain/report/presentation/ReportController.java
- src/main/resources/application.yml
- 말씀드린대로 신고 API를 하나로 합쳤습니다.
- 신고 목록 조회 API 개발 중 follow에서 repository를 converter로 넘기는 것에 대한 이야기를 했던 것이 떠올랐습니다.
처음엔 저도 넘기는 방식으로 만들었으나, repository를 3개나 넘겨야 했기 때문에 다른 방식을 생각해보았습니다.
추후에 더 나은 방식으로의 변경 가능성이 있고, 객체지향에 대해서도 생각해볼 수 있는 것 같아 여기에 적어놓습니다 !
Closes #28
> ✨ [FEAT]: Report API 개발

- src/main/java/depth/jeonsilog/domain/calendar/application/CalendarService.java
- src/main/java/depth/jeonsilog/domain/calendar/converter/CalendarConverter.java
- src/main/java/depth/jeonsilog/domain/calendar/domain/Calendar.java
- src/main/java/depth/jeonsilog/domain/calendar/domain/repository/CalendarRepository.java
- src/main/java/depth/jeonsilog/domain/calendar/dto/CalendarRequestDto.java
- src/main/java/depth/jeonsilog/domain/calendar/dto/CalendarResponseDto.java
- src/main/java/depth/jeonsilog/domain/calendar/presentation/CalendarController.java
> ✨ [FEAT]: 포토캘린더 API 개발

- src/main/java/depth/jeonsilog/domain/exhibition/application/ExhibitionService.java
- src/main/java/depth/jeonsilog/domain/exhibition/converter/ExhibitionConverter.java
- src/main/java/depth/jeonsilog/domain/exhibition/domain/Exhibition.java
- src/main/java/depth/jeonsilog/domain/exhibition/domain/repository/ExhibitionRepository.java
- src/main/java/depth/jeonsilog/domain/exhibition/dto/ExhibitionRequestDto.java
- src/main/java/depth/jeonsilog/domain/exhibition/dto/ExhibitionResponseDto.java
- src/main/java/depth/jeonsilog/domain/exhibition/presentation/ExhibitionController.java
- 전시회 순서 변경 RequestDto를 주의깊게 봐주시면 좋을 것 같습니다. Wrapper 클래스가 있어요.
- 나머지도 빠르게 마무리할게요 ㅜ
Closes #41
> ✨ [FEAT]: Exhibition 추가 API 개발

- src/main/java/depth/jeonsilog/domain/place/application/PlaceService.java
- src/main/java/depth/jeonsilog/domain/place/domain/repository/PlaceRepository.java
- src/main/java/depth/jeonsilog/domain/user/application/UserService.java
빼먹은 것 위주의 간단한 변경입니다!
Closes #46
> 🐛 [FIX]: place 검색 조건 수정 및 유저 탈퇴 시 s3에서 프로필 이미지 삭제

- src/main/java/depth/jeonsilog/domain/alarm/application/AlarmService.java
- src/main/java/depth/jeonsilog/domain/alarm/converter/AlarmConverter.java
- src/main/java/depth/jeonsilog/domain/alarm/domain/Alarm.java
- src/main/java/depth/jeonsilog/domain/alarm/dto/AlarmResponseDto.java
- src/main/java/depth/jeonsilog/domain/alarm/presentation/AlarmController.java
- src/main/java/depth/jeonsilog/domain/report/converter/ReportConverter.java
- src/main/java/depth/jeonsilog/domain/report/domain/Report.java
- src/main/java/depth/jeonsilog/domain/report/dto/ReportResponseDto.java
- src/main/java/depth/jeonsilog/domain/review/application/ReviewService.java
- src/main/java/depth/jeonsilog/domain/review/domain/repository/ReviewRepository.java
- src/main/java/depth/jeonsilog/domain/review/dto/ReviewResponseDto.java
- src/main/java/depth/jeonsilog/domain/review/presentation/ReviewController.java
- src/main/java/depth/jeonsilog/domain/user/application/UserService.java
- src/main/java/depth/jeonsilog/domain/user/converter/UserConverter.java
- src/main/java/depth/jeonsilog/domain/user/domain/User.java
- src/main/java/depth/jeonsilog/domain/user/dto/UserResponseDto.java
- src/main/java/depth/jeonsilog/domain/user/presentation/UserController.java
- boolean -> Boolean 타입 변경 때문에 파일 변경이 많습니다. 어려운 코드는 없는 것 같아요.
- 신고 내역 조회 response에 확인 여부가 없는 것 같아서 추가했습니다.
Closes #47
> ✨ [FEAT]: User, Alarm, Review API 개발 (대면 회의 후)

- src/main/java/depth/jeonsilog/domain/exhibition/domain/Exhibition.java
- src/main/java/depth/jeonsilog/domain/exhibition/domain/repository/ExhibitionRepository.java
- src/main/java/depth/jeonsilog/domain/openApi/application/AddService.java
- src/main/java/depth/jeonsilog/domain/openApi/application/SaveService.java
- src/main/java/depth/jeonsilog/domain/openApi/presentation/AddController.java
- src/main/java/depth/jeonsilog/domain/place/converter/PlaceConverter.java
- src/main/java/depth/jeonsilog/domain/place/domain/ClosedDays.java
- src/main/java/depth/jeonsilog/domain/place/domain/Place.java
- src/main/java/depth/jeonsilog/domain/place/dto/PlaceRequestDto.java
- src/main/java/depth/jeonsilog/domain/place/dto/PlaceResponseDto.java
최초 저장 (save)는 로컬에서 rds 연결 후 직접 진행하겠습니다. 프로젝트에서 단 한 번만 호출하는 api입니다.
데이터 수정 (modify) 로직의 실행 시간 및 주기는 결정 후 적용하겠습니다.
데이터 갱신(add)은 최초 저장이 완료된 후부터 실행합니다. 마찬가지로 실행 시간 및 주기는 결정 후 적용하겠습니다.
- 데이터 갱신은 현재 저장되어 있는 데이터에 오늘 날짜로 조회되는 데이터를 추가합니다.
- 이미 있는 데이터는 추가하지 않습니다.
Closes #53
> ✨ [FEAT]: 전시회 갱신(추가 저장) 로직 개발

- src/main/java/depth/jeonsilog/domain/alarm/application/AlarmService.java
- src/main/java/depth/jeonsilog/domain/alarm/domain/repository/AlarmRepository.java
- src/main/java/depth/jeonsilog/domain/alarm/presentation/AlarmController.java
- src/main/java/depth/jeonsilog/domain/exhibition/application/ExhibitionService.java
- src/main/java/depth/jeonsilog/domain/exhibition/domain/repository/ExhibitionRepository.java
- src/main/java/depth/jeonsilog/domain/follow/application/FollowService.java
- src/main/java/depth/jeonsilog/domain/follow/domain/repository/FollowRepository.java
- src/main/java/depth/jeonsilog/domain/follow/presentation/FollowController.java
- src/main/java/depth/jeonsilog/domain/interest/application/InterestService.java
- src/main/java/depth/jeonsilog/domain/interest/domain/repository/InterestRepository.java
- src/main/java/depth/jeonsilog/domain/interest/presentation/InterestController.java
- src/main/java/depth/jeonsilog/domain/openApi/application/AddService.java
- src/main/java/depth/jeonsilog/domain/place/application/PlaceService.java
- src/main/java/depth/jeonsilog/domain/rating/application/RatingService.java
- src/main/java/depth/jeonsilog/domain/rating/domain/repository/RatingRepository.java
- src/main/java/depth/jeonsilog/domain/rating/presentation/RatingController.java
- src/main/java/depth/jeonsilog/domain/report/application/ReportService.java
- src/main/java/depth/jeonsilog/domain/review/application/ReviewService.java
- src/main/java/depth/jeonsilog/domain/review/domain/repository/ReviewRepository.java
- src/main/java/depth/jeonsilog/domain/review/presentation/ReviewController.java
- src/main/java/depth/jeonsilog/domain/user/application/UserService.java
- src/main/java/depth/jeonsilog/domain/user/domain/repository/UserRepository.java
- src/main/java/depth/jeonsilog/domain/user/presentation/UserController.java
- src/main/resources/application.yml
변경 파일이 많습니다. 하지만, Controller, Service, Repository의 묶음으로 페이징 처리를 했기에 복잡하지는 않습니다.
User
- 사용자 목록 조회 20개
- 검색 20개
이렇게 있는데, 사용자 목록 조회 API는 없는 API가 아닌가? 싶습니다.
그래서 유저는 검색만 페이징 처리를 했습니다.
Closes #44
> ✨ [FEAT]: 목록 조회 API 페이징 처리

- .github/workflows/deploy.yml
> 🚀 [DEPLOY]: 8차 배포

- src/main/java/depth/jeonsilog/domain/reply/domain/repository/ReplyRepository.java
- src/main/java/depth/jeonsilog/domain/review/domain/repository/ReviewRepository.java
- src/main/java/depth/jeonsilog/domain/user/application/UserService.java
@Where 사용으로 인한 Soft Delete를 조회할 수 없어서 삭제되지 않아, 참조 무결성이 위반되었습니다.
@Where을 무시하고 조회할 수 있는 방법으로 모두 삭제하여 해결했습니다!
Closes #68
> 🐛 [FIX]: 회원탈퇴 로직 수정

- .gitignore
- build.gradle
- src/main/java/depth/jeonsilog/domain/alarm/application/AlarmService.java
- src/main/java/depth/jeonsilog/domain/auth/converter/AuthConverter.java
- src/main/java/depth/jeonsilog/domain/exhibition/application/ExhibitionService.java
- src/main/java/depth/jeonsilog/domain/fcm/application/FcmService.java
- src/main/java/depth/jeonsilog/domain/follow/application/FollowService.java
- src/main/java/depth/jeonsilog/domain/follow/presentation/FollowController.java
- src/main/java/depth/jeonsilog/domain/rating/application/RatingService.java
- src/main/java/depth/jeonsilog/domain/rating/presentation/RatingController.java
- src/main/java/depth/jeonsilog/domain/reply/application/ReplyService.java
- src/main/java/depth/jeonsilog/domain/reply/presentation/ReplyController.java
- src/main/java/depth/jeonsilog/domain/review/application/ReviewService.java
- src/main/java/depth/jeonsilog/domain/review/presentation/ReviewController.java
- src/main/java/depth/jeonsilog/domain/user/application/UserService.java
- src/main/java/depth/jeonsilog/domain/user/converter/UserConverter.java
- src/main/java/depth/jeonsilog/domain/user/domain/User.java
- src/main/java/depth/jeonsilog/domain/user/dto/UserRequestDto.java
- src/main/java/depth/jeonsilog/domain/user/dto/UserResponseDto.java
- src/main/java/depth/jeonsilog/domain/user/presentation/UserController.java
- src/main/java/depth/jeonsilog/global/config/FcmConfig.java
> ✨ [FEAT]: FCM을 활용한 푸시 알림 구현, User 엔티티 컬럼 변경

- src/main/java/depth/jeonsilog/domain/user/application/UserService.java
전시회 쪽은 이미 처리가 되어 있는 것으로 보이는데, 
제가 착각을 하는 것인지 같이 생각해보면 좋을 것 같아요!
Closes #59
> 🐛 [FIX]: 유저 및 전시회 image null, not null 처리

- src/main/java/depth/jeonsilog/domain/fcm/application/FcmService.java
- src/main/java/depth/jeonsilog/domain/review/application/ReviewService.java
- src/main/java/depth/jeonsilog/domain/review/converter/ReviewConverter.java
- src/main/java/depth/jeonsilog/domain/review/domain/Review.java
- src/main/java/depth/jeonsilog/domain/review/domain/repository/ReviewRepository.java
- src/main/java/depth/jeonsilog/domain/review/dto/ReviewRequestDto.java
- src/main/java/depth/jeonsilog/domain/review/dto/ReviewResponseDto.java
- src/main/java/depth/jeonsilog/domain/review/presentation/ReviewController.java
- src/main/java/depth/jeonsilog/domain/user/application/UserService.java
- src/main/java/depth/jeonsilog/domain/user/converter/UserConverter.java
- src/main/java/depth/jeonsilog/domain/user/dto/UserResponseDto.java
- src/main/java/depth/jeonsilog/domain/user/presentation/UserController.java
> ✨ [FEAT]: 추가 API 개발 및 수정 사항 반영

- src/main/java/depth/jeonsilog/domain/openApi/application/AddService.java
- src/main/java/depth/jeonsilog/domain/openApi/application/SaveService.java
- src/main/java/depth/jeonsilog/domain/openApi/presentation/AddController.java
- src/main/java/depth/jeonsilog/domain/openApi/presentation/ModifyController.java
- src/main/java/depth/jeonsilog/domain/openApi/presentation/SaveController.java
- src/main/java/depth/jeonsilog/domain/user/converter/UserConverter.java
- src/main/java/depth/jeonsilog/domain/user/dto/UserResponseDto.java
- src/main/resources/application-swagger.yml
유저 정보 조회 API 관리자 확인 여부 포함 - 같은 ResDto를 사용하고 있기에, 본인뿐만 아니라 타 유저 정보 조회 API에도 isAdmin이 들어갔습니다.. 조금 찝찝하지만요.. 참고하시면 될 것 같아용
그 외에는 스웨거 설정 조금이랑 데이터 저장 관련 약간의 변동 사항입니다!
Closes #59
> 🐛 [FIX]: 추가적인 수정 사항 반영

- src/main/java/depth/jeonsilog/domain/alarm/application/AlarmService.java
- src/main/java/depth/jeonsilog/domain/fcm/application/FcmService.java
- 기획팀 의견대로 활동 / 전시 알림의 내용을 수정했습니다.
- 활동 알림의 내용이 없어짐에따라 `FcmService` 쪽 코드의 수정이 필요했는데, 알림을 만드는 기능과 푸시하는 기능을 분리하면 좋겠다는 생각을 해서 메서드를 분리했습니다. `makeActiveAlarm`과 `makeExhibitionAlarm` 의 코드가 중복되는 부분이 많은 점이 조금 걸리긴 합니다.. 그런데 테스트하기도 힘들고 더 건드렸다가 어떻게 될지 몰라 불안한 마음에 이대로 하겠습니다..
Closes #77
> ♻️[REFACTOR]: 푸시 알림 내용, 코드 리팩토링

- appspec.yml
ubuntu -> root로 변경했습니다!
https://lionking-yg.tistory.com/25
Closes #59
> 🐛 [FIX]: Permission denied 해결

- src/main/java/depth/jeonsilog/domain/openApi/application/AddService.java
- src/main/java/depth/jeonsilog/domain/openApi/application/SaveService.java
- src/main/java/depth/jeonsilog/domain/reply/application/ReplyService.java
- src/main/java/depth/jeonsilog/domain/reply/converter/ReplyConverter.java
- src/main/java/depth/jeonsilog/domain/reply/domain/repository/ReplyRepository.java
- src/main/java/depth/jeonsilog/domain/reply/dto/ReplyResponseDto.java
- src/main/java/depth/jeonsilog/domain/reply/presentation/ReplyController.java
- src/main/java/depth/jeonsilog/domain/report/application/ReportService.java
- src/main/java/depth/jeonsilog/domain/report/converter/ReportConverter.java
- src/main/java/depth/jeonsilog/domain/report/dto/ReportResponseDto.java
- src/main/java/depth/jeonsilog/domain/report/presentation/ReportController.java
- src/main/java/depth/jeonsilog/domain/review/domain/repository/ReviewRepository.java
Place가 null인 전시회 상세 정보 수정 시 -> Place가 null인 모든 전시회에게 영향이 미치기에 null인 Place도 새로운 row로 추가하도록 만들었습니다.
신고 내역 조회 시, reply의 clickId가 필요하기에, 추가했습니다
Closes #59
> 🐛 [FIX]: Place null 수정 시 일괄 수정 문제 해결

- src/main/java/depth/jeonsilog/domain/alarm/application/AlarmService.java
- 이전에 같이 AlarmService 코드 볼때 얘기했던 부분인데 쩜쩜으로 계속 이어지는게 찝찝해서 따로 뺐습니다..ㅎㅎ
Closes #83
> 🐛[FIX]: 나의 감상평에 내가 댓글 작성 시 알림 생성되지 않도록 수정

- src/main/java/depth/jeonsilog/domain/user/application/UserService.java
개괄
EntityNotFound 조회 및 삭제하기 위한 엔티티 find 시 발생할 뿐만 아니라,
해당 엔티티의 컬럼(필드)값을 수정하기 위해서도 엔티티를 조회해야 하는데, 이때 찾을 수 없음이 문제였습니다.
문제
reply 삭제 시, review는 review.updateReplyNum을 수행하기 위해 review를 조회해야 합니다.
하지만, @Where로 인해 Soft Delete는 조회되지 않고, Status=Delete인 review는 조회되지 않기 때문에.. 에러가 발생했구요..
해결
테이티브 쿼리로 @Where을 무시하여 Status에 상관없이 review를 조회한 후, ....
Closes #59
> 🐛 [FIX]: 회원 탈퇴 로직 수정

- src/main/java/depth/jeonsilog/domain/alarm/application/AlarmService.java
- src/main/java/depth/jeonsilog/domain/user/application/UserService.java
> 🚀 [DEPLOY]: 틈새 배포 

- src/main/java/depth/jeonsilog/domain/exhibition/application/ExhibitionService.java
- src/main/java/depth/jeonsilog/domain/user/application/UserService.java
> 🚑 [HOTFIX]: 전시회 랜덤 조회 로직 수정

- build.gradle
- src/main/java/depth/jeonsilog/domain/openApi/application/AddService.java
- src/main/java/depth/jeonsilog/domain/openApi/application/SaveService.java
- src/main/resources/application.yml
open api 서비스키 하루 제한 때문에 나눠서 진행할게용
퍼블릭 액세스 차단했기 때문에, 배포 후 addController(openAPI) 요청 보내서 업데이트 하겠습니다.
Closes #91
> [FEAT]: 10페이지까지 전시회/전시공간 update

- src/main/java/depth/jeonsilog/domain/openApi/application/AddService.java
> [FEAT]: 데이터 갱신 마무리

- src/main/java/depth/jeonsilog/domain/openApi/application/AddService.java
> [FEAT]: @Scheduled 적용

- src/main/java/depth/jeonsilog/domain/openApi/application/AddService.java
> 🚀  [FEAT]: @Scheduled 적용

- src/main/java/depth/jeonsilog/domain/calendar/domain/Calendar.java
- src/main/java/depth/jeonsilog/domain/user/domain/User.java
- src/main/java/depth/jeonsilog/domain/user/domain/UserLevel.java
1. 노션에도 적어놓았는데, 저번 달 회의 때부터 발견했던 것으로, 배포 환경에서 ddl-auto: update로 돌려야만 실행이 되는 기현상이 있습니다. 분명히 데모데이 이후 건드린 적이 없는데 말이죠 ..
2. 유사하게 해당 PR은 컬럼을 건드린 것이고, ddl 작성을 통한 DB 수정이 필요합니다. 이 시점에서.. 1번과 같은 문제의 찝찝함도 있으니 시원하게 ddl-auto: create를 돌리고 싶다는 생각이 있는데, 아무래도 데이터가 문제겠죠.. 데이터 처리보다는 양에 관한 문제이므로 create를 돌리는 것이 아예 못 할 짓은 아님으로 보인다는 하나의 의견입니다.
3. 이번 변경 사항으로 돌아와서 .. 첫 감상평 작성 여부를 확인해야 하기 때문에 UserLevel에 'DONE' 추가했습니다 (EXIST로 했었는데, SQL 명령어랑 겹칠 듯 하네용)
Closes #98
> [REFACTOR]: 유지보수 엔티티 컬럼 추가

- src/main/generated/depth/jeonsilog/domain/alarm/domain/QAlarm.java
- src/main/generated/depth/jeonsilog/domain/auth/domain/QToken.java
- src/main/generated/depth/jeonsilog/domain/calendar/domain/QCalendar.java
- src/main/generated/depth/jeonsilog/domain/common/QBaseEntity.java
- src/main/generated/depth/jeonsilog/domain/exhibition/domain/QExhibition.java
- src/main/generated/depth/jeonsilog/domain/follow/domain/QFollow.java
- src/main/generated/depth/jeonsilog/domain/interest/domain/QInterest.java
- src/main/generated/depth/jeonsilog/domain/place/domain/QPlace.java
- src/main/generated/depth/jeonsilog/domain/rating/domain/QRating.java
- src/main/generated/depth/jeonsilog/domain/reply/domain/QReply.java
- src/main/generated/depth/jeonsilog/domain/report/domain/QReport.java
- src/main/generated/depth/jeonsilog/domain/review/domain/QReview.java
- src/main/generated/depth/jeonsilog/domain/stop/domain/QStop.java
- src/main/generated/depth/jeonsilog/domain/user/domain/QUser.java
- src/main/java/depth/jeonsilog/domain/exhibition/application/ExhibitionService.java
- src/main/java/depth/jeonsilog/domain/exhibition/domain/repository/ExhibitionRepository.java
- src/main/java/depth/jeonsilog/domain/exhibition/presentation/ExhibitionController.java
홈 화면에 나타나는 전시회 목록이 기존에는 관리자 설정 10개 + 무한이었습니다.
카테고리가 추가되어, 종료 14일 전, 시작 날짜로부터 8일 미만 경과, 
서울특별시 종로구 + 국립현대미술관 서울관 + 대림미술관 + 일민미술관 추가하였습니다.
요구사항이 많아서 if문이 조금 많다는 점이 있습니다.
develop 브랜치 pull 받고 pr 올렸는데 changed files에 포함되어 있네요
Exhibition 쪽만 봐주시면 될 듯 합니다
Closes #102
> [FEAT]: 홈 화면 전시회 카테고리별 전시회 목록 조회 추가

- src/main/java/depth/jeonsilog/domain/calendar/application/CalendarService.java
- src/main/java/depth/jeonsilog/domain/calendar/converter/CalendarConverter.java
- src/main/java/depth/jeonsilog/domain/calendar/dto/CalendarRequestDto.java
- src/main/java/depth/jeonsilog/domain/calendar/dto/CalendarResponseDto.java
> [FEAT]: caption 컬럼 추가에 따른 로직 추가

- src/main/generated/depth/jeonsilog/domain/user/domain/QUser.java
- src/main/java/depth/jeonsilog/domain/auth/converter/AuthConverter.java
- src/main/java/depth/jeonsilog/domain/calendar/application/CalendarService.java
- src/main/java/depth/jeonsilog/domain/calendar/converter/CalendarConverter.java
- src/main/java/depth/jeonsilog/domain/calendar/dto/CalendarRequestDto.java
- src/main/java/depth/jeonsilog/domain/calendar/dto/CalendarResponseDto.java
- src/main/java/depth/jeonsilog/domain/review/application/ReviewService.java
- src/main/java/depth/jeonsilog/domain/user/domain/User.java
switch case문에서 ->를 사용하는 문법은 case마다 break가 필요 없다고 합니다
Closes #101
> [FEAT]: 유저 레벨 변경 로직 작성

- src/main/java/depth/jeonsilog/domain/exhibition/domain/Exhibition.java
- src/main/java/depth/jeonsilog/domain/exhibition/domain/repository/ExhibitionRepository.java
- src/main/java/depth/jeonsilog/domain/openApi/application/ModifyService.java
혹시 몰라 오차 생각해서 0시 1분으로 했습니다!!
Closes #106
> [FEAT]: 매일 Operating Keyword 수정

- src/main/java/depth/jeonsilog/domain/stop/application/StopService.java
- src/main/java/depth/jeonsilog/domain/stop/dto/StopResponseDto.java
> :sparkles: [FEAT]: 유저 정지 조회 response에 최초 여부 추가

- src/main/java/depth/jeonsilog/domain/report/application/ReportService.java
- src/main/java/depth/jeonsilog/domain/report/domain/repository/ReportRepository.java
- src/main/java/depth/jeonsilog/domain/report/presentation/ReportController.java
- `Report.user.id` + `reportType` + `reportedId` 세 개로 DB 조회해서 이미 있으면 예외처리 했습니다.
Closes #116
> :sparkles: [FEAT]: 같은 사용자가 여러 번 신고했을 때 한 번으로 처리

- src/main/java/depth/jeonsilog/domain/reply/converter/ReplyConverter.java
- src/main/java/depth/jeonsilog/domain/reply/dto/ReplyResponseDto.java
- src/main/java/depth/jeonsilog/domain/review/converter/ReviewConverter.java
- src/main/java/depth/jeonsilog/domain/review/dto/ReviewResponseDto.java
- src/main/java/depth/jeonsilog/domain/user/converter/UserConverter.java
- src/main/java/depth/jeonsilog/domain/user/dto/UserResponseDto.java
응답 값에 유저 레벨 및 (나의 감상평 개수) 추가했습니다.
Converter를 사용하는 것이 개발할 때는 편한 점이 부각되었는데, Dto의 값을 수정할 때에는 조금 불편할 수 있겠다는 생각도 드네요 !! 
Closes #119
> ✨ [FEAT]: 유저 조회 시 응답 값 추가

- src/main/java/depth/jeonsilog/domain/review/converter/ReviewConverter.java
- src/main/java/depth/jeonsilog/domain/review/dto/ReviewResponseDto.java
[알림 -> 감상평 -> 전시회 바로가기] 를 구현하기 위한 수정사항입니다.
Closes #122
> :sparkles: [FEAT]: 감상평 조회에 exhibitionID 추가

- src/main/generated/depth/jeonsilog/domain/report/domain/QReport.java
- src/main/java/depth/jeonsilog/domain/exhibition/domain/repository/ExhibitionRepository.java
전시 자체가 7일도 안하는 것들의 경우, 시작일로부터 8일 미만에 해당되기 때문에 종료되었더라도 조회가 되었습니다.
ON_DISPLAY만 조회하도록 했습니다 !
Closes #125
> [FIX]: 새로 시작된 전시 조회 시 ON_DISPLAY만

- src/main/java/depth/jeonsilog/domain/exhibition/application/ExhibitionService.java
- src/main/java/depth/jeonsilog/domain/exhibition/domain/repository/ExhibitionRepository.java
- src/main/resources/application.yml
> [FIX]: 전시회 랜덤 로직 수정
